### PR TITLE
Branch4.6

### PR DESCRIPTION
**Pull request by piperdenney**
4.6 Pair with @brianhansen345

### CODE REVIEW

**Comment by brianhansen345** [comment]
Hey Piper,

Would you be willing to send your code for 4.4 (vampires)? I turned in what
I had but I'd love to compare what I did with what you did.

Thanks,
Brian

**Comment by brianhansen345** [comment]
One quick note.

I think when we were doing the "Secret Agents" assignment we thought that
"index" was a particular method or in some way had a given significance.
Though, I don't think that's the case. It's the brackets [ ]  that do the
thing that we want (index the string into characters), rather than the word
index. You can replace the word "index" in the code with any other value
and it works the same, as long as it's in the brackets the same way.

**Comment by brianhansen345** [comment]
Except when it's a method, as in .index.

Sorry for all the emails.

**Comment by piperdenney** [comment]
Hey! Just seeing all of these- if you ever need a quicker response just
email me directly because I get so many github alerts that I don't check
them all  :). I can totally send my vampires code and thanks for clearing
up the index thing- that totally makes sense!

**Pull request merged**
